# Generated by Django 4.0.2 on 2022-02-23 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
            ],
            options={
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4, verbose_name='Ключ')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Начало действия')),
                ('stop_date', models.DateField(default=datetime.datetime(2022, 3, 25, 16, 48, 42, 547053), verbose_name='Окончание действия')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
